---

name: Ansible-Test
on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code from Github
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install latest Ansible through pip
      run: pip install ansible

    - name: Output python and ansible versions
      run: |
        python --version
        ansible --version

    - name: Create ansible.cfg with correct roles_path
      run: printf '[defaults]\nroles_path=../' > ansible.cfg

    - name: Basic role syntax check
      run: ansible-playbook tests/test.yml -i tests/inventory --syntax-check

    - name: Real run
      run: ansible-playbook tests/test.yml -i tests/inventory --connection=local || echo "Done"

    - name: Second run to check for indempotence, allowing one 'change'
      run: ansible-playbook tests/test.yml -i tests/inventory --connection=local | grep -q 'changed=1.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)

    - name: Output contents of flussonic.conf for manual check
      run: sudo cat /etc/flussonic/flussonic.conf

    - name: Setup serverspec (as root, so we can run it as root)
      run: |
        sudo apt-get install -y ruby
        sudo ruby -v
        sudo gem install serverspec

    - name: Run serverspec (as root, to be able to check everything)
      run: sudo rake spec
